export const array = [
    "Yes", 
    "No", 
    "Dream on!", 
    "Nice try", 
    "Sounds like something a wolf would say.",
    "Full moon?",
    "Doubtful",
    "Things look bad.",
    "Don't count on it.",
    "Rely on it",
    "It's always the loud ones",
    "The lady doth protest too much, methinks",
    "That's a definite.",
    "Nope, no, and hell no.",
    "Talk is cheap",
    "Sure as Satan",
    "You know the answer already, my dear.",
    "Of course.",
    "The villager doesn't fall far from the tree.",
    "Statistically speaking, that's not how statistics work.",
    "You don't even go here.",
    "I think the Seer might know",
    "Where's your Witch now?",
    "Where's the Seer when you need them.",
    "Hahaha",
    "Hm? Oh sorry, thought you were dead already. Sure, yes, whatever.",
    "Yeah, nah",
    "Nah, yeah",
    "A quiet villager is as useful as a dead one.",
    "The hunter would know what to do.",
    "Ummm.. What Would Seer Do?",
    "Maybe. Entertain me. I want to hear their defense",
    "Trust your instincts",
    "You're not doing very well, eh.",
    "What a question, Mark.",
    "Hm, I have many eyes, but I don't see your point."
]